### ISSUE TITLE
Pins are not displayed

### ISSUE THREAD

**Issue by mtugnoli** [eugene-zhary/Xamarin.Forms-GpsNote#3]
I have set my API key,
and all seem run ok, map, create pin etc.
but pins creates are not showed in map !
Have an idea ?

**Comment by eugene-zhary** [comment]
@mtugnoli hi, it is all okay, only favorite pins are display on map. You can check it at the second tab.
![photo_2021-06-24_16-42-06](https://user-images.githubusercontent.com/55335403/123273242-25c5ab00-d50b-11eb-828a-5cfc291ce547.jpg)

**Comment by mtugnoli** [comment]
Yes it is ok,

I have two little implements 

- Set on current position on startup
- add picture to each pin (with phone camera )

**Comment by eugene-zhary** [comment]
@mtugnoli Thank you, so much for your suggestion about improving my app!
